{% set name = "attrs" %}
{% set version = "24.3.0" %}
{% set sha256 = "8f5c07333d543103541ba7be0e2ce16eeee8130cb0b3f9238ab904ce1e85baff" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - hatch-fancy-pypi-readme
  run:
    - python >={{ python_min }}

test:
  requires:
    - coverage
    - hypothesis
    - pympler
    - six
    - python {{ python_min }}
  imports:
    - attr

about:
  home: https://attrs.readthedocs.io/en/stable/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: attrs is the Python package that will bring back the joy of writing classes by relieving you from the drudgery of implementing object protocols (aka dunder methods).

  description: |
    attrs is the Python package that will bring back the joy of writing
    classes by relieving you from the drudgery of implementing object
    protocols (aka dunder methods). Its main goal is to help you to write
    concise and correct software without slowing down your code. For that, it
    gives you a class decorator and a way to declaratively define the
    attributes on that class:
  doc_url: https://attrs.readthedocs.io/en/stable/
  dev_url: https://github.com/python-attrs/attrs

extra:
  recipe-maintainers:
    - CJ-Wright
    - licode
    - nicoddemus
    - jochym
